# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1420695587);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1420696750);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1420717477);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1420701780);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.lastDir", "/home/seema/Pictures/Git - About Version Control_files");
user_pref("browser.download.panel.shown", true);
user_pref("browser.download.save_converter_index", 0);
user_pref("browser.migration.version", 15);
user_pref("browser.newtabpage.blocked", "{\"38LHRZF2KBO67tUgA5liTQ==\":1,\"z9XM+swa8a9jwaVE7wzlVQ==\":1}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 6);
user_pref("browser.preferences.advanced.selectedTabIndex", 1);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20140410211200");
user_pref("browser.slowStartup.averageTime", 5796);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20140410211200");
user_pref("browser.startup.homepage_override.mstone", "28.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":0}");
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1420709264006");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1420709267103");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1420795667103");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAccepted", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1420535585017");
user_pref("datareporting.policy.dataSubmissionPolicyResponseTime", "1420536379779");
user_pref("datareporting.policy.dataSubmissionPolicyResponseType", "accepted-info-bar-button-pressed");
user_pref("datareporting.policy.firstRunTime", "1416585296215");
user_pref("datareporting.sessions.current.activeTicks", 1);
user_pref("datareporting.sessions.current.firstPaint", 7026);
user_pref("datareporting.sessions.current.main", 1034);
user_pref("datareporting.sessions.current.sessionRestored", 7173);
user_pref("datareporting.sessions.current.startTime", "1420734140493");
user_pref("datareporting.sessions.current.totalTime", 20);
user_pref("datareporting.sessions.currentIndex", 41);
user_pref("datareporting.sessions.previous.40", "{\"s\":1420701659953,\"a\":87,\"t\":17507,\"c\":true,\"m\":31,\"fp\":779,\"sr\":880}");
user_pref("datareporting.sessions.prunedIndex", 39);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 11);
user_pref("extensions.blocklist.pingCountVersion", 11);
user_pref("extensions.bootstrappedAddons", "{\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"28.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\"},\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"28.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\"},\"webapps-team@lists.launchpad.net\":{\"version\":\"3.0.2\",\"type\":\"extension\",\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/webapps-team@lists.launchpad.net\"}}");
user_pref("extensions.databaseSchema", 15);
user_pref("extensions.enabledAddons", "%7B2e1445b0-2682-11e1-bfc2-0800200c9a66%7D:2013.09.20.beta,ubufox%40ubuntu.com:2.8,online-accounts%40lists.launchpad.net:0.5,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:28.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20140527.01.11");
user_pref("extensions.installCache", "[{\"name\":\"app-system-local\",\"addons\":{\"online-accounts@lists.launchpad.net\":{\"descriptor\":\"/usr/lib/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/online-accounts@lists.launchpad.net\",\"mtime\":1397697896000,\"rdfTime\":1390969548000}}},{\"name\":\"app-system-share\",\"addons\":{\"{2e1445b0-2682-11e1-bfc2-0800200c9a66}\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{2e1445b0-2682-11e1-bfc2-0800200c9a66}\",\"mtime\":1397697896000,\"rdfTime\":1379719396000},\"webapps-team@lists.launchpad.net\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/webapps-team@lists.launchpad.net\",\"mtime\":1397697896000,\"rdfTime\":1397665356000},\"ubufox@ubuntu.com\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"mtime\":1397697896000,\"rdfTime\":1381435136000}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1397697838000,\"rdfTime\":1397165556000},\"langpack-en-ZA@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"mtime\":1397166457000},\"langpack-en-GB@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"mtime\":1397166457000}}}]");
user_pref("extensions.lastAppVersion", "28.0");
user_pref("extensions.lastPlatformVersion", "28.0");
user_pref("extensions.pendingOperations", false);
user_pref("gecko.buildID", "20140410211200");
user_pref("gecko.mstone", "28.0");
user_pref("idle.lastDailyNotification", 1420703401);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.database", "{\"files\":[{\"fingerprint\":\"bef31684dea6d61b3a169a58d14cb11\",\"exists\":true,\"page\":1,\"zoom\":\"auto\",\"scrollLeft\":0,\"scrollTop\":577}]}");
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1420709264);
user_pref("places.history.expiration.transient_current_max_pages", 101224);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("plugins.notifyMissingFlash", false);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1420613178);
user_pref("toolkit.startup.last_success", 1420734141);
user_pref("toolkit.telemetry.previousBuildID", "20140410211200");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1421838855);
